name: CMake

on: [push, pull_request] 

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{matrix.platform.name}}
    runs-on: ${{matrix.platform.os}}

    defaults:
      run:
        shell: ${{matrix.platform.shell}}

    strategy:
      matrix:
        platform:
        - { name: Windows (MSVC),              os: windows-latest, shell: pwsh, flags: -A Win32, artifact-suffix: windows-msvc }
        - { name: Windows (MinGW-w64 + GCC),   os: windows-latest, shell: 'msys2 {0}', msystem: mingw32, msys-env: mingw-w64-i686, artifact-suffix: windows-mingw }
        - { name: Windows (MinGW-w64 + Clang), os: windows-latest, shell: 'msys2 {0}', msystem: clang32, msys-env: mingw-w64-clang-i686, artifact-suffix: windows-mingw-clang }
        - { name: Linux,                       os: ubuntu-latest,  shell: sh, artifact-suffix: linux-x64 }
        - { name: MacOS,                       os: macos-latest,   shell: sh, artifact-suffix: macos }

    steps:
    - name: Set up MSYS2
      if: matrix.platform.shell == 'msys2 {0}'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.platform.msystem}}
        install: ${{matrix.platform.msys-env}}-cc ${{matrix.platform.msys-env}}-cmake ${{matrix.platform.msys-env}}-ninja

    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B build -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.platform.flags}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --build build --config ${{env.BUILD_TYPE}} --target install

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: skc-tools-${{matrix.platform.artifact-suffix}}
        path: install/*
