name: CMake

on: [push, pull_request] 

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{matrix.platform.name}}
    runs-on: ${{matrix.platform.os}}

    defaults:
      run:
        shell: ${{matrix.platform.shell}}

    strategy:
      matrix:
        platform:
        - { name: Windows (MSVC),      os: windows-latest, shell: pwsh, flags: -A Win32 }
        - { name: Windows (MinGW-w64), os: windows-latest, shell: 'msys2 {0}' }
        - { name: Linux,               os: ubuntu-latest,  shell: sh }
        - { name: MacOS,               os: macos-latest,   shell: sh }

    steps:
    - name: Set up MSYS2
      if: matrix.platform.shell == 'msys2 {0}'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: mingw-w64-i686-gcc mingw-w64-i686-cmake mingw-w64-i686-ninja

    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.platform.flags}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
